CREATE TABLE [dbo].[ProjectItems]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [ProjectId] UNIQUEIDENTIFIER NOT NULL, 
    [Name] NVARCHAR(255) NOT NULL, 
    [FileId] UNIQUEIDENTIFIER NULL, 
    [RowVersion] ROWVERSION NOT NULL
)
